=== FranCampo/LDM/Examen 17-03-2021/arbol.dtd
<!ELEMENT arbol (lugares,personas)>
<!ELEMENT lugares (lugar+)>
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre,padre?,madre?,nacimiento)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT padre (#PCDATA)>
<!ELEMENT madre (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ATTLIST lugar nombre CDATA #REQUIRED>
<!ATTLIST lugar pais CDATA #REQUIRED>
<!ATTLIST nacimiento lugar CDATA #REQUIRED>
<!ATTLIST nacimiento fecha CDATA #IMPLIED>

=== FranCampo/LDM/Examen 17-03-2021/5_dtdxsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE arbol SYSTEM "arbol.dtd">
<arbol>
  <lugares>
    <lugar nombre="Valencia" pais="España" />
    <lugar nombre="Gandía" pais="España" />
    <lugar nombre="Marsella" pais="Francia" />
  </lugares>
  <personas>
    <persona>
      <nombre>Pedro Ramírez Dupont</nombre>
      <padre>Juan Ramírez Amigo</padre>
      <madre>Jeanne Dupont</madre>
      <nacimiento lugar="Valencia" fecha="1942-07-14" />
    </persona>
    <persona>
      <nombre>Juan Ramírez Amigo</nombre>
      <nacimiento lugar="Gandía" fecha="1918-11-19" />
    </persona>
    <persona>
      <nombre>Jeanne Dupont</nombre>
      <nacimiento lugar="Marsella" />
    </persona>
  </personas>
</arbol>
