=== FranCampo/LDM/Palencia/Palencia.dtd
<!ELEMENT Palencia (Habitantes, Comunidad, Bares, Ocios)>
<!ELEMENT Bares (Bar+)>
<!ELEMENT Bar (Nombre, Coste, Movilidad_reducida, Recomendable, Direccion, Tipo, Link)>
<!ELEMENT Ocios (Ocio+)>
<!ELEMENT Ocio (Nombre, Ubicacion)>
<!ELEMENT Habitantes (#PCDATA)>
<!ELEMENT Comunidad (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Coste (#PCDATA)>
<!ELEMENT Movilidad_reducida (#PCDATA)>
<!ELEMENT Recomendable (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>
<!ELEMENT Tipo (#PCDATA)>
<!ELEMENT Link (#PCDATA)>
<!ELEMENT Ubicacion (#PCDATA)>

=== FranCampo/LDM/Palencia/Palencia.XML
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Palencia SYSTEM "Palencia.dtd">
<Palencia>
    <Habitantes>75000</Habitantes>
    <Comunidad>CyL</Comunidad>
    <Bares>
        <Bar>
            <Nombre>Bar Nuevo Arenas</Nombre>
            <Coste>4/5</Coste>
            <Movilidad_reducida>No</Movilidad_reducida>
            <Recomendable>4/5</Recomendable>
            <Direccion>Av. de Asturias, 6, 34005 Palencia</Direccion>
            <Tipo>Restaurante</Tipo>
            <Link>https://goo.gl/maps/N9JXhQcj5fMMeJmCA</Link>
        </Bar>
         <Bar>
            <Nombre>LaBelleEpoque</Nombre>
            <Coste>4/5</Coste>
            <Movilidad_reducida>No</Movilidad_reducida>
            <Recomendable>4/5</Recomendable>
            <Direccion>Calle Cardenal Almaraz, 4, 34005 Palencia</Direccion>
            <Tipo>Pub</Tipo>
            <Link>https://goo.gl/maps/mNxQ8gBEWV3tvuLp6</Link>
        </Bar>
         <Bar>
            <Nombre>La Mejillonera</Nombre>
            <Coste>4/5</Coste>
            <Movilidad_reducida>Si</Movilidad_reducida>
            <Recomendable>4/5</Recomendable>
            <Direccion>Calle los Soldados, 7, 34001 Palencia</Direccion>
            <Tipo>Restaurante</Tipo>
            <Link>https://goo.gl/maps/yTcJ7rrrDt1R8Eqb6</Link>
        </Bar>
         <Bar>
            <Nombre>Zambra</Nombre>
            <Coste>4/5</Coste>
            <Movilidad_reducida>No</Movilidad_reducida>
            <Recomendable>4/5</Recomendable>
            <Direccion>Calle Estrada, 5, 34002 Palencia</Direccion>
            <Tipo>Pub</Tipo>
            <Link>https://goo.gl/maps/os7fphzKi6QkHRmUA</Link>
        </Bar>
         <Bar>
            <Nombre>Basi</Nombre>
            <Coste>4/5</Coste>
            <Movilidad_reducida>Si</Movilidad_reducida>
            <Recomendable>3/5</Recomendable>
            <Direccion>Calle de Renault - Espa√±a, 10, 34004 Palencia</Direccion>
            <Tipo>Restaurante</Tipo>
            <Link>https://goo.gl/maps/iUVbWfzbqRvQfYWu8</Link>
        </Bar>
    </Bares>
    <Ocios>
        <Ocio>
            <Nombre>Bowling Sport</Nombre>
            <Ubicacion>Av. de Casado del Alisal, 22, 34001 Palencia</Ubicacion>
        </Ocio>
        <Ocio>
            <Nombre>Teatro Principal de Palencia</Nombre>
            <Ubicacion>Calle Burgos, 3, 34001 Palencia</Ubicacion>
        </Ocio>
        <Ocio>
            <Nombre>Multicines Avenida</Nombre>
            <Ubicacion>Av. Valladolid, 10, BAJO, 34002 Palencia</Ubicacion>
        </Ocio>
    </Ocios>
</Palencia>
