<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softwareLibre [
<!ELEMENT softwareLibre (aplicaciones, licencias)>
<!ELEMENT licencias (licencianombreID*)>
<!ELEMENT aplicaciones (aplicacion*)>
<!ELEMENT aplicacion (version*)>
<!ELEMENT licencianombreID (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ATTLIST aplicacion nombre CDATA #REQUIRED>
<!ATTLIST version licencia CDATA #REQUIRED>
<!ATTLIST version fechaPublicacion CDATA #IMPLIED>]>
<softwareLibre>
    <aplicaciones>
        <aplicacion nombre="Inkscape">
            <version licencia="GPL v2" fechaPublicacion="17/08/2010">0.47</version>
            <version licencia="GPL v2" fechaPublicacion="17/08/2010">0.48</version>
            <version licencia="GPL v2" fechaPublicacion="14/08/2011">0.48.2</version>
        </aplicacion>
        <aplicacion nombre="PostgreSQL">
            <version licencia="BSD2" fechaPublicacion="15/09/2011">9.1.0</version>
            <version licencia="BSD2">9.1.3</version>
        </aplicacion>
    </aplicaciones>
    <licencias>
        <licencianombreID>GPL v2</licencianombreID>
        <licencianombreID>BSD2</licencianombreID>
        <licencianombreID>Apache v2</licencianombreID>
    </licencias>
</softwareLibre>