=== FranCampo/LDM/Practica 26 de febrero/Ejercicio5.xsd
<?xml version="1.0"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://www.w3schools.com"
    xmlns="https://www.w3schools.com"
    elementFormDefault="qualified">
    <xs:element name="cartelera">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="peliculas">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pelicula">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="estreno" type="xs:string"/>
                                        <xs:element name="director" type="xs:string"/>
                                        <xs:element name="identificador" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cine">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Nombre" type="xs:string"/>
                                        <xs:element name="sala" type="xs:string"/>
                                        <xs:element name="titulo" type="xs:string"/>
                                        <xs:element name="sesiones">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="sesion" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FranCampo/LDM/Practica 26 de febrero/Ejercicio5(xsd).xml
<?xml version="1.0" encoding="UTF-8"?>
<cartelera 
    xmlns="https://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.w3schools.com/xml Ejercicio5.xsd">
    <peliculas>
        <pelicula>
            <titulo>La invencion de Hugo</titulo>
            <estreno>2011</estreno>
            <director>Martin Scorsese</director>
            <identificador>1</identificador>
        </pelicula>
        <pelicula>
            <titulo>Jhon Carter</titulo>
            <estreno>2012</estreno>
            <director>Andrew Stanton</director>
            <identificador>2</identificador>
        </pelicula>
        <pelicula>
            <titulo>Intocable</titulo>
            <estreno>2012</estreno>
            <director>Oliver Nakashe</director>
            <identificador>3</identificador>
        </pelicula>
    </peliculas>
    <cines>
        <cine>
            <Nombre>ABC el Saler</Nombre>
            <sala>6</sala>
            <titulo>La invencion de Hugo</titulo>
            <sesiones>
                <sesion>18:00</sesion>
                <sesion>20:25</sesion>
                <sesion>22:50</sesion>
            </sesiones>
        </cine>
        <cine>
            <Nombre>Lys</Nombre>
            <sala>3</sala>
            <titulo>Jhon Carter</titulo>
            <sesiones>
                <sesion>16:20</sesion>
                <sesion>18:50</sesion>
            </sesiones>
        </cine>
    </cines>
</cartelera>
